### ISSUE TITLE
在点击房间配置后崩溃

### ISSUE THREAD

**Issue by sxxtandfxxk233** [carrot-hu23/dst-admin-go#11]
2023/06/06 14:28:43 manager.go:55: token=a5GSoRK6U3iHacJcPmTS5Gt7B2wsGs-p0MO5JB4qdp8%3D
2023/06/06 14:28:43 interceptorHandler.go:84: cookiName: admin
2023/06/06 14:28:43 interceptorHandler.go:85: sessionID: a5GSoRK6U3iHacJcPmTS5Gt7B2wsGs-p0MO5JB4qdp8%3D
2023/06/06 14:28:43 clusterService.go:113: str: []
panic: read dst blocklist.txt error:
open /home/leaderone/.klei/DoNotStarveTogether/Cluster3/blocklist.txt: no such file or directory

goroutine 755533 [running]:
dst-admin-go/service.ReadBlocklistFile()
        /root/mine/dst/dst-admin-go/service/clusterService.go:115 +0x119
dst-admin-go/service.GetGameConfog.func4()
        /root/mine/dst/dst-admin-go/service/clusterService.go:434 +0x2b
created by dst-admin-go/service.GetGameConfog
        /root/mine/dst/dst-admin-go/service/clusterService.go:433 +0x1af

**Comment by hujinbo23** [comment]
你现在哪个release版本，以前的版本需要你默认把房间所有的配置都设置好，你这个问题，只需要在 ~/.klei/DoNotStarveTogether/Cluster3 这目录下 创建下 blocklist.txt adminlist.txt 文件就行了

最新的 release 版本已经解决这个问题了，建议直接下载 1.1.6.bata 版本

**Comment by sxxtandfxxk233** [comment]
1.1.5，下载1.1.6之后就没有崩溃了

**Comment by sxxtandfxxk233** [comment]
请问如何生成一个新世界？是设置好房间之后直接启动还是需要替换一些文件呢

**Comment by sxxtandfxxk233** [comment]
在我将房间设置好以后直接启动，提示启动成功了，但是启动开关就会弹回去没有任何反应

**Comment by hujinbo23** [comment]
请检查 steamcmd 和 饥荒 路径是否设置正确（使用绝对路径），有问题贴日志信息
